# Generated by Django 5.1.7 on 2025-03-21 03:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('idInformation', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('urlWeb', models.URLField()),
                ('embedding', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Informacion',
                'verbose_name_plural': 'Informaciones',
                'db_table': 'Informacion',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('idSocialMedia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('url', models.URLField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('idInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Informacion.informacion')),
            ],
            options={
                'verbose_name': 'SocialMedia',
                'verbose_name_plural': 'SocialMedias',
                'db_table': 'SocialMedia',
            },
        ),
    ]
