# Generated by Django 5.1.7 on 2025-03-21 04:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='specialty',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
